import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Topbar from "./_components/Topbar";
import Sidebar from "./_components/navigation/Sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={clsx(
                    inter.className,
                    "flex h-screen gap-4 bg-primary p-8"
                )}
            >
                <Sidebar />
                <main className="flex h-full w-full flex-col gap-4">
                    <Topbar />
                    <div className="scrollbar-none overflow-y-auto">
                        {children}
                    </div>
                </main>
            </body>
        </html>
    );
}
