import {
    AdjustmentsHorizontalIcon,
    ArrowRightOnRectangleIcon,
    Bars3Icon,
    DocumentArrowUpIcon,
    GlobeAltIcon,
    TicketIcon,
} from "@heroicons/react/24/outline";
import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";

import NavSection from "./_components/NavSection";
import User from "./_components/User";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={clsx(
                    inter.className,
                    "flex h-screen gap-4 bg-primary p-8"
                )}
            >
                <nav className="flex h-full w-60 shrink-0 flex-col gap-4 overflow-y-auto">
                    <header className="flex h-14 items-center gap-3 text-text">
                        <TicketIcon className="h-14 w-14" />
                        <span className="text-2xl font-medium">STREAMER</span>
                    </header>
                    <User username={"Thomas"} email={"t.ferb1@gmail.com"} />
                    <div className="flex flex-col gap-8">
                        <NavSection
                            label={"Menu"}
                            buttons={[
                                {
                                    icon: <GlobeAltIcon className="h-6 w-6" />,
                                    label: "Discover",
                                    url: "/",
                                },
                                {
                                    icon: <Bars3Icon className="h-6 w-6" />,
                                    label: "My List",
                                    url: "/list",
                                },
                                {
                                    icon: (
                                        <DocumentArrowUpIcon className="h-6 w-6" />
                                    ),
                                    label: "Upload",
                                    url: "/upload",
                                },
                            ]}
                        />
                        <NavSection
                            label={"General"}
                            buttons={[
                                {
                                    icon: (
                                        <AdjustmentsHorizontalIcon className="h-6 w-6" />
                                    ),
                                    label: "Settings",
                                    url: "/settings",
                                },
                                {
                                    icon: (
                                        <ArrowRightOnRectangleIcon className="h-6 w-6" />
                                    ),
                                    label: "Logout",
                                    url: "/logout",
                                },
                            ]}
                        />
                    </div>
                </nav>
                <main className="h-full w-full">{children}</main>
            </body>
        </html>
    );
}
